/* Generated By:JavaCC: Do not edit this line. DBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE = 9;
  /** RegularExpression Id. */
  int TABLE = 10;
  /** RegularExpression Id. */
  int DROP = 11;
  /** RegularExpression Id. */
  int DESC = 12;
  /** RegularExpression Id. */
  int INSERT = 13;
  /** RegularExpression Id. */
  int INTO = 14;
  /** RegularExpression Id. */
  int DELETE = 15;
  /** RegularExpression Id. */
  int FROM = 16;
  /** RegularExpression Id. */
  int SELECT = 17;
  /** RegularExpression Id. */
  int SHOW = 18;
  /** RegularExpression Id. */
  int TABLES = 19;
  /** RegularExpression Id. */
  int NULL = 20;
  /** RegularExpression Id. */
  int PRIMARY = 21;
  /** RegularExpression Id. */
  int KEY = 22;
  /** RegularExpression Id. */
  int FOREIGN = 23;
  /** RegularExpression Id. */
  int REFERENCES = 24;
  /** RegularExpression Id. */
  int AS = 25;
  /** RegularExpression Id. */
  int WHERE = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int NOT = 29;
  /** RegularExpression Id. */
  int IS = 30;
  /** RegularExpression Id. */
  int VALUES = 31;
  /** RegularExpression Id. */
  int SEMICOLON = 32;
  /** RegularExpression Id. */
  int LEFT_PAREN = 33;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 34;
  /** RegularExpression Id. */
  int PERIOD = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int QUOTE = 37;
  /** RegularExpression Id. */
  int ASTERISK = 38;
  /** RegularExpression Id. */
  int UNDERSCORE = 39;
  /** RegularExpression Id. */
  int EQUAL_TO = 40;
  /** RegularExpression Id. */
  int NOT_EQUAL = 41;
  /** RegularExpression Id. */
  int LESS_THAN = 42;
  /** RegularExpression Id. */
  int GREATER_THAN = 43;
  /** RegularExpression Id. */
  int GREATER_THAN_OR_EQUAL_TO = 44;
  /** RegularExpression Id. */
  int LESS_THAN_OR_EQUAL_TO = 45;
  /** RegularExpression Id. */
  int INT_VALUE = 46;
  /** RegularExpression Id. */
  int CHAR_STRING = 47;
  /** RegularExpression Id. */
  int DATE_VALUE = 48;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 49;
  /** RegularExpression Id. */
  int OTHERS = 50;
  /** RegularExpression Id. */
  int SIGN = 51;
  /** RegularExpression Id. */
  int DIGIT = 52;
  /** RegularExpression Id. */
  int ALPHABET = 53;
  /** RegularExpression Id. */
  int NN = 54;
  /** RegularExpression Id. */
  int NNNN = 55;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 56;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create\"",
    "\"table\"",
    "\"drop\"",
    "\"desc\"",
    "\"insert\"",
    "\"into\"",
    "\"delete\"",
    "\"from\"",
    "\"select\"",
    "\"show\"",
    "\"tables\"",
    "\"null\"",
    "\"primary\"",
    "\"key\"",
    "\"foreign\"",
    "\"references\"",
    "\"as\"",
    "\"where\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"is\"",
    "\"values\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"\\\'\"",
    "\"*\"",
    "\"_\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "<INT_VALUE>",
    "<CHAR_STRING>",
    "<DATE_VALUE>",
    "<LEGAL_IDENTIFIER>",
    "<OTHERS>",
    "<SIGN>",
    "<DIGIT>",
    "<ALPHABET>",
    "<NN>",
    "<NNNN>",
    "<NON_QUOTE_CHARACTER>",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
  };

}
